### ISSUE TITLE
Where to put overall config?

### ISSUE THREAD

**Issue by JoaoCarabetta** [base-dos-dados/bases#9]
1. CLI deve rodar de qlqr lugar do computador
2. secrets deve estar nessa pasta

lugar do config: `~/.basedosdados`

config.yaml

```
metadata_path: 
bucket_name:
templates_path:

user:
   name:
   email:
   website:
   photo:
```
